name: Build

on:
  workflow_dispatch: 

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          npm ci || npm i

      - name: Expo prebuild
        run: |
          npx expo prebuild -p android

      - name: Build Android
        run: |
          cd android
          chmod +x gradlew
          ./gradlew ":app:assembleRelease"
      
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: 📤 Create Pre-Release with APKs
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.run_number }}"
          name: "App Build ${{ env.RELEASE_DATE }}"
          body: "Build automatique hebdomadaire pour Android."
          prerelease: true
          artifacts: |
            android/app/build/outputs/apk/release/*.apk
